### ISSUE TITLE
How does one integrate connections to wired sensors on windows/door?

### ISSUE THREAD

**Issue by stefanolarentis** [datjan/esp32-homekit-securitysystem#1]
Hi,

great program! I believe the 4 switches shown in the readme are used to define the alarm status in Homekit (Home, Away, Night, Off), which is great!

![image](https://user-images.githubusercontent.com/35013107/166086932-4855cc67-ec5e-4211-952e-8bf16b288268.png)

I find this image in this git [taligentx/dscKeybusInterface](https://github.com/taligentx/dscKeybusInterface) which could be helpful for the English public.

How one does integrate connections to wired sensors on windows/doors? I believe in a separate git you had this drawing (very explanatory). I would incredible to create a "sensor" for each door as shown in the image above.

![image](https://user-images.githubusercontent.com/35013107/166087008-25700e5f-ce7b-4c95-bdc2-2000c6095012.png)

Are you considering to extend [esp32-homekit-securitysystem](https://github.com/datjan/esp32-homekit-securitysystem) to include sensing options rather than only change the status of the alarm.

I would like to contribute, but I am new to HomeSpan!
Great start!

**Comment by stefanolarentis** [comment]
Update: I think you use your triggered channel adding in series all your alarm sensors?

I think it would be so nice to have sensing for individual zones/channels.

**Comment by datjan** [comment]
Hi,

I don't use this sketch with contact sensors.

I have an existing ABUS security system and wired the interface with the ESP32. Because of that the logic is really simple.

Close the contact and you will get the following state:
GPIO16 = homekit state away
GPIO17 = homekit state triggered
GPIO18 = homekit state night
GPIO19 = homekit state stay

If you want to use contact sensors directly you have to wire it that way and use additional switches. Use NO instead of NC contact sensors or change the wires from normal LOW to normal HIGH.

If you want to use individual zones, like HomeKit supports, you should buy a professional security system. This is not possible with a simple ESP32 sketch.

greetings
Jan
